### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Invictaz** [Reino17/bashgemist#1]
Werkt dit ook op de Android versie van Xidel? Ik zag je wel posten in hun Github maar weet dus niet hoever je zelf bent gekomen.

Vraag 2: vervangt dit batchgemist of blijven daar updates voor komen?

**Comment by Reino17** [comment]
Xidel's queries veranderen niet, die blijven hetzelfde als voor Linux, dus ik denk het haast wel. Probeer het eens, zou ik zeggen. Ben zeer benieuwd.
Ik zelf heb er geen tijd meer in gestoken.

Zie https://github.com/Reino17/BatchGemist/commit/ae9926447914df7413da78d3c7e93d17262b4883.
