### ISSUE TITLE
NPO livestreams geven http error 500

### ISSUE THREAD

**Issue by joopmartens** [Reino17/bashgemist#3]
Het uitvoeren van bashgemist.sh met de NPO livestreams geeft een http error 500 i.p.v. een URL:

`# ./bashgemist.sh https://www.npostart.nl/live/npo-1
Error:
err:FODC0002: Internet/HTTP Error: 500 when talking to: http://ida.omroep.nl/app.php/LI_NL1_4188102?token=5km863vlmntr5l8joe7gqvp2s3
Possible backtrace:
  $00000000006202B9: Q{http://www.benibela.de/2012/pxp/extensions}serialize-json + 489
  $0000000000553D44: perhaps TXQTermTryCatch + 169188 ? but unlikely
  $000000000051EB14: perhaps TXQTermBinaryOp + 5012 ? but unlikely
  $0000000000506876: perhaps TXQTermModule + 6854 ? but unlikely
  $000000000045F148: perhaps ? ? but unlikely`

`Call xidel with --trace-stack to get an actual backtrace
Error:
err:XPST0008: Unknown variable: $json
bashgemist: geen video's beschikbaar.`

De niet livestream links lijken wel nog goed te functioneren:

`# ./bashgemist.sh https://www.npostart.nl/nos-journaal/28-02-2017/POW_03375558
https://nl-ams-p11-am3.cdn.streamgate.nl/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTQ4MzY1MTcsInVyaSI6Ilwvdm9kXC9ucG9cL3VzcFwvbnBvXC9obHNfdW5lbmNyeXB0ZWRcL1BPV18wMzM3NTU1OFwvUE9XXzAzMzc1NTU4X3Y0LmlzbSIsImNsaWVudF9pcCI6IjgzLjI0Ny4zMy44NiJ9.pCkBEICg11yrAlW1q7DaX30s-zGwHm1CjIBEEUljEaE/vod/npo/usp/npo/hls_unencrypted/POW_03375558/POW_03375558_v4.ism/POW_03375558_v4-audio=128000-video=1109000.m3u8`

**Comment by Reino17** [comment]
Hallo Joop. Je hebt gelijk.
```sh
xidel -s "https://www.npostart.nl/live/npo-1" -e 'json(concat("http://ida.omroep.nl/app.php/",//npo-player/@media-id,"?token=",json("http://ida.omroep.nl/app.php/auth")/token))'
Error:
err:FODC0002: Internet/HTTP Error: 500
when talking to: http://ida.omroep.nl/app.php/LI_NL1_4188102?token=3r9d72h0opmhc1invqm9a58hl0
[...]
```
Het ziet er naar uit dat de NPO de oude API nu helemaal heeft afgeschreven. Misschien was het wel een foutje dat de livestreams van NPO 1,2 en 3 het tot nu toe nog deden.  
Met de nieuwe API zijn ook deze streams van DRM voorzien, dus dat gaat 'm niet worden. Einde verhaal, jammer genoeg.

Ik zal de extractor één dezer dagen verwijderen. Bedankt voor het melden.
