### ISSUE TITLE
 Fout: Xidel niet gevonden!

### ISSUE THREAD

**Issue by vespino** [Reino17/bashgemist#4]
Ik krijg nu ineens de volgende melding:

Fout: Xidel niet gevonden!
Installeer Xidel a.u.b. om dit script te kunnen gebruiken.

Vreemd omdat ik voorheen deze melding nooit kreeg en het script altijd prima werkte. Ik heb Xidel nooit geïnstalleerd omdat ik het script op mijn Synology draai en het daar dus altijd werkte, ook zonder Xidel kennelijk.

Tips?

**Comment by Reino17** [comment]
Aan dat gedeelte heb ik sinds de eerste commit geen wijzigingen toegebracht, dus zo lang je `xidel` hebt geïnstalleerd, of in ieder geval in `/usr/bin` hebt zitten, dan zou dat gewoon moeten werken.
Zonder `xidel` werkt het script niet.

**Comment by vespino** [comment]
Ik heb afgelopen week mijn synology bijgewerkt... wellicht hebben ze xidel verwijderd?

**Comment by vespino** [comment]
Probleem opgelost. Xidel kan namelijk makkelijk worden geïnstalleerd op Synology blijkt nu.

**Comment by Reino17** [comment]
Nu ben ik toch wel benieuwd hoe en waarom je mijn script op je Synology NAS gebruikt. Ik heb er zelf ook een, maar heb nooit de behoefte gehad om Xidel / BashGemist daarop aan de praat te krijgen. Kun je me dat vertellen?
Overigens heb je Xidel handmatig daarop moeten installeren, denk ik? Voor zover ik weet zit Xidel niet in de package-manager in ieder geval.

**Comment by vespino** [comment]
Waarom niet? Ik had geen behoefte om hier speciaal een VM voor in te richten als het gewoon rechtstreeks op de Synology draait. Doel was om geautomatiseerd downloads binnen te halen.

Xidel heb ik inderdaad handmatig moeten installeren wat een fluitje van een cent bleek.

**Comment by Reino17** [comment]
> Waarom niet?

Mijn vraag was helemaal niet afkeurend bedoeld! Ik stelde 'm puur uit interesse. Dus, bedankt.

**Comment by vespino** [comment]
Je vroeg “waarom” waarop mijn antwoord was “waarom niet” ;) Je vraag voelde niet als afkeurend.
